[package]
name = "fatum_graphics"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.24.0", features = ["derive"] }
glam = { version = "0.30.9", features = ["bytemuck"] }
glfw = "0.60.0"
glow = { version = "0.16.0", features = ["debug_automatic_glGetError"] }
